WIP

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -34,11 +34,11 @@ download_path="$ASDF_DOWNLOAD_PATH/$release_file"
 url="$GH_REPO/releases/download/v${ASDF_INSTALL_VERSION}/$release_file"
 
 echo "Debugging vars:"
-echo "ASDF_DOWNLOAD_PATH: $ASDF_DOWNLOAD_PATH" 
-echo "ASDF_INSTALL_VERSION: $ASDF_INSTALL_VERSION" 
-echo "release_file $release_file"
-echo "download_path $download_path"
-echo "url $url"
+echo "* ASDF_DOWNLOAD_PATH: $ASDF_DOWNLOAD_PATH" 
+echo "* ASDF_INSTALL_VERSION: $ASDF_INSTALL_VERSION" 
+echo "* release_file $release_file"
+echo "* download_path $download_path"
+echo "* url $url"
 
 curl -fsSL -L -o "$download_path" "$url" || fail "Could not download $url"
 
@@ -49,8 +49,8 @@ else
 fi
 
 # Extract contents of tar.gz file into the download directory
-echo "####About to extract####"
-tar -xzf "$download_path" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+# echo "####About to extract####"
+# tar -xzf "$download_path" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
 
 # Remove the tar.gz file since we don't need to keep it
-rm "$download_path"
+# rm "$download_path"
