SEMI WORKING VERSION

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -38,7 +38,7 @@ echo "####About to extract####"
 echo "release path: $release_path"
 echo "download path: $ASDF_DOWNLOAD_PATH"
 
-tar -xzf "$release_path" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+tar -xzf "$release_path" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
 
 # Remove the tar.gz file since we don't need to keep it
-# rm "$release_path"
+rm "$release_path"
