WIP

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -48,10 +48,11 @@ else
   fail "Download seems to have failed. File not found at $download_path"
 fi
 
-exit 1
 # Extract contents of tar.gz file into the download directory
-# echo "####About to extract####"
-# tar -xzf "$download_path" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+echo "####About to extract####"
+tar -xzf "$download_path" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
 
 # Remove the tar.gz file since we don't need to keep it
-# rm "$download_path"
+rm "$download_path"
+
+exit 1
