WIP

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -1,5 +1,4 @@
 #!/usr/bin/env bash
-
 set -euo pipefail
 
 current_script_path=${BASH_SOURCE[0]}
@@ -10,14 +9,33 @@ source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+# Determine OS and architecture
+os=""
+arch=""
+
+case "$(uname -s)" in
+  Darwin) os="darwin" ;;
+  Linux) os="linux" ;;
+  MINGW*|MSYS*|CYGWIN*) os="windows" ;;
+  *) fail "Unsupported operating system: $(uname -s)" ;;
+esac
+
+case "$(uname -m)" in
+  x86_64) arch="amd64" ;;
+  arm64|aarch64) arch="arm64" ;;
+  i*86) arch="386" ;;
+  *) fail "Unsupported architecture: $(uname -m)" ;;
+esac
+
+release_file="${TOOL_NAME}_${ASDF_INSTALL_VERSION}_${os}_${arch}.tar.gz"
+release_path="$ASDF_DOWNLOAD_PATH/$release_file"
 
 # Download tar.gz file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
 echo "This is the download tar"
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$ASDF_DOWNLOAD_PATH" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+# Extract contents of tar.gz file into the download directory
+tar -xzf "$release_path" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
 
 # Remove the tar.gz file since we don't need to keep it
-rm "$release_file"
+rm "$release_path"
